app:
  version: "1.0.1"
  name: "isotcp"
  env: "development"

network:
  fw_ip: "172.16.58.20"

server:
  - name: "fw"
    ip: "172.16.58.20"
    ports: [2020, 2021]
    is_enable: true
    is_default: true
  - name: "sw"
    ip: "172.16.58.19"
    ports: [3020, 3021]
    is_enable: true
    is_default: false


output:
  packet_log_path: "output/packets.log"
  is_need_packet_log: false
  input_csv_path: "output/input.csv"
  output_csv_path: "output/output.csv"
  durations_csv: "output/durations.csv"

limits:
  max_records: 10000
  max_packet_logs: 20

log: 
  test: "test data"
  metadata:
    # service: "tcp"
    level: "trace"
    path: "logs/app.log"
    apply_to_global: true
  console:
    enable: true
    pipe: true
    fields_exclude: ["test"]
  rotation:
    size: 1024000
    interval: "daily"
    count: 20
  array_sample:
    - type: "type 1"
      size: 102400 # size in KB
      count: 10
      interval: "hourly"
    - type: "type 2"
      size: 202400 # size in KB
      count: 20
      interval: "weekly"

crossnetwork:
  net:
    - src: "sipa"
      dest: "fe1"
      oid: "1.3.6.1.4.1.10.2.21"
      index: 0
    - src: "sipa"
      dest: "fe2"
      oid: "1.3.6.1.4.1.10.2.22"
      index: 1
